---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: ['diff']
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint
  - repo: https://opendev.org/openstack/bashate.git
    rev: 2.1.1
    hooks:
      - id: bashate
        args: [-v, --max-line-length, '100']
  - repo: https://github.com/vlotorev/buildroot-utils
    rev: 81a34ae0afb16f26db7d9135427ce071538c0fa1
    hooks:
      - id: lint-buildroot
        exclude: |
            (?x)^(
                package/rtl-test-stop/.*|
                package/mcom03-vpu-libs/mcom03-vpu-libs.mk|
            )$
  - repo: https://github.com/pycqa/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        args: [--quiet, --max-line-length=100]
  - repo: https://github.com/myint/rstcheck
    rev: v6.1.2
    hooks:
      - id: rstcheck
  - repo: local
    hooks:
      - id: check-ddrinit-defconfig
        name: check-ddrinit-defconfig
        language: system
        entry: >-
          bash -c 'diff --color
          <(grep BR2_PACKAGE_DDRINIT_DEFCONFIGS configs/mcom03_defconfig)
          <(grep BR2_PACKAGE_DDRINIT_DEFCONFIGS configs/mcom03fc_defconfig)'
        pass_filenames: false
