################################################################################
#
# mcom03-sbl
#
################################################################################

MCOM03_SBL_VERSION = $(call qstrip,$(BR2_PACKAGE_MCOM03_SBL_REPO_VERSION))
MCOM03_SBL_SITE = ssh://gerrit.elvees.com:29418/mcom03/sbl
MCOM03_SBL_SITE_METHOD = git
MCOM03_SBL_LICENSE = GPLv2
MCOM03_SBL_DEPENDENCIES = host-toolchain-mipsel-elvees-elf32 host-bootrom-tools \
	arm-trusted-firmware ddrinit uboot
MCOM03_SBL_INSTALL_TARGET_OPTS = DESTDIR=$(BINARIES_DIR) install/fast

MCOM03_SBL_PATH_MKSBIMAGE = $(HOST_BOOTROM_TOOLS_INSTALL_DIR)/mksbimage
MCOM03_SBL_PATH_OTPCREATOR = $(HOST_BOOTROM_TOOLS_INSTALL_DIR)/otpcreator

MCOM03_SBL_CONF_OPTS += -DIMAGES_PATH=$(BINARIES_DIR)
MCOM03_SBL_CONF_OPTS += -DCMAKE_TOOLCHAIN_FILE=$(HOST_TOOLCHAIN_MIPSEL_ELVEES_ELF32_CMAKE_FILE)
MCOM03_SBL_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=

MCOM03_SBL_CONF_OPTS += -DDDRINIT_DTB_MAP_FILE="$(shell readlink -f $(BR2_MCOM03_DDRINIT_DTB_MAP))"
MCOM03_SBL_CONF_OPTS += -DBUILD_ID=$(call qstrip,$(BUILD_ID))

ifneq ($(MCOM03_SBL_OVERRIDE_SRCDIR),)
MCOM03_SBL_CONF_OPTS += -DGIT_DIR=$(MCOM03_SBL_OVERRIDE_SRCDIR)
else
MCOM03_SBL_CONF_OPTS += -DGIT_DIR=$(MCOM03_SBL_DL_DIR)/git
endif

ifneq ($(BR2_PACKAGE_MCOM03_SBL_RECOVERY_ENABLE),)
MCOM03_SBL_CONF_OPTS += -DRECOVERY_ENABLE=ON
endif

MCOM03_SBL_SBIMG_SEC_TYPE = $(call qstrip,$(BR2_PACKAGE_MCOM03_SBL_SBIMG_SEC_TYPE))

ifneq ($(MCOM03_SBL_SBIMG_SEC_TYPE),none)
MCOM03_SBL_SBIMG_ROOT_CA = $(@D)/certs/rootCA.der
MCOM03_SBL_SBIMG_NON_ROOT_CA = $(@D)/certs/nonRootCA.der
MCOM03_SBL_SBIMG_FW_CA = $(@D)/certs/fwCA.der
MCOM03_SBL_SBIMG_FW_PK = $(@D)/certs/fwPrivateKey.der

define MCOM03_SBL_EXTRACT_CERTS
	mkdir -p $(@D)/certs
	$(TAR) xf $(BR2_PACKAGE_MCOM03_SBL_SBIMG_CERTS_TAR) -C $(@D)/certs
endef

MCOM03_SBL_POST_EXTRACT_HOOKS += MCOM03_SBL_EXTRACT_CERTS
MCOM03_SBL_POST_RSYNC_HOOKS += MCOM03_SBL_EXTRACT_CERTS
endif

MCOM03_SBL_CONF_OPTS += \
	-DSBIMG_SEC_TYPE=$(MCOM03_SBL_SBIMG_SEC_TYPE) \
	-DSBIMG_ENC_DSN=$(BR2_PACKAGE_MCOM03_SBL_SBIMG_ENC_DSN) \
	-DSBIMG_ENC_DUK=$(BR2_PACKAGE_MCOM03_SBL_SBIMG_ENC_DUK) \
	-DSBIMG_ENC_KEY=$(BR2_PACKAGE_MCOM03_SBL_SBIMG_ENC_KEY) \
	-DSBIMG_ROOT_CA=$(MCOM03_SBL_SBIMG_ROOT_CA) \
	-DSBIMG_NON_ROOT_CA=$(MCOM03_SBL_SBIMG_NON_ROOT_CA) \
	-DSBIMG_FW_CA=$(MCOM03_SBL_SBIMG_FW_CA) \
	-DSBIMG_FW_PK=$(MCOM03_SBL_SBIMG_FW_PK) \
	-DSBIMG_MAKE_RECOVERY=$(BR2_PACKAGE_MCOM03_SBL_SBIMG_MAKE_RECOVERY)

ifneq ($(BR2_PACKAGE_MCOM03_SBL_ADDITIONAL_VARIABLES),)
MCOM03_SBL_CONF_OPTS += $(call qstrip,$(BR2_PACKAGE_MCOM03_SBL_ADDITIONAL_VARIABLES))
endif

MCOM03_SBL_MAKE_ENV = \
	PATH=$(MCOM03_SBL_PATH_MKSBIMAGE):$(MCOM03_SBL_PATH_OTPCREATOR):$(call qstrip,$(BR_PATH))

$(eval $(cmake-package))
