################################################################################
#
# mcom03-baremetal-tools-arm64
#
################################################################################

MCOM03_BAREMETAL_TOOLS_ARM64_VERSION = master
MCOM03_BAREMETAL_TOOLS_ARM64_SITE = ssh://gerrit.elvees.com:29418/mcom03/baremetal-tools
MCOM03_BAREMETAL_TOOLS_ARM64_SITE_METHOD = git
MCOM03_BAREMETAL_TOOLS_ARM64_LICENSE = MIT
MCOM03_BAREMETAL_TOOLS_ARM64_LICENSE_FILES = LICENSE

MCOM03_BAREMETAL_TOOLS_ARM64_INSTALL_TARGET = NO
MCOM03_BAREMETAL_TOOLS_ARM64_INSTALL_IMAGES = YES

MCOM03_BAREMETAL_TOOLS_ARM64_CONF_OPTS += -DCMAKE_INSTALL_PREFIX="/"

MCOM03_BAREMETAL_TOOLS_ARM64_DESTDIR = $(BINARIES_DIR)/baremetal-tools
MCOM03_BAREMETAL_TOOLS_ARM64_MAKE = $(MAKE) -C $(@D)

define MCOM03_BAREMETAL_TOOLS_ARM64_INSTALL_IMAGES_CMDS
	$(MCOM03_BAREMETAL_TOOLS_ARM64_MAKE) DESTDIR=$(MCOM03_BAREMETAL_TOOLS_ARM64_DESTDIR) install
endef

$(eval $(cmake-package))
