################################################################################
#
# mcom03-baremetal-tools
#
################################################################################

MCOM03_BAREMETAL_TOOLS_VERSION = master
MCOM03_BAREMETAL_TOOLS_SITE = ssh://gerrit.elvees.com:29418/mcom03/baremetal-tools
MCOM03_BAREMETAL_TOOLS_SITE_METHOD = git
MCOM03_BAREMETAL_TOOLS_LICENSE = MIT
MCOM03_BAREMETAL_TOOLS_LICENSE_FILES = LICENSE
MCOM03_BAREMETAL_TOOLS_DEPENDENCIES = host-toolchain-mipsel-elvees-elf32

MCOM03_BAREMETAL_TOOLS_INSTALL_TARGET = NO
MCOM03_BAREMETAL_TOOLS_INSTALL_IMAGES = YES

MCOM03_BAREMETAL_TOOLS_CONF_OPTS += -DCMAKE_TOOLCHAIN_FILE=$(HOST_TOOLCHAIN_MIPSEL_ELVEES_ELF32_CMAKE_FILE)
MCOM03_BAREMETAL_TOOLS_CONF_OPTS += -DCMAKE_INSTALL_PREFIX="/"

MCOM03_BAREMETAL_TOOLS_DESTDIR = $(BINARIES_DIR)/baremetal-tools
MCOM03_BAREMETAL_TOOLS_MAKE = $(MAKE) -C $(@D)

define MCOM03_BAREMETAL_TOOLS_INSTALL_IMAGES_CMDS
	$(MCOM03_BAREMETAL_TOOLS_MAKE) DESTDIR=$(MCOM03_BAREMETAL_TOOLS_DESTDIR) install
endef

$(eval $(cmake-package))
