################################################################################
#
# mcom03-felix
#
################################################################################

MCOM03_FELIX_VERSION = master
MCOM03_FELIX_SITE_METHOD = git

MCOM03_FELIX_SITE = ssh://gerrit.elvees.com:29418/mcom03/felix
MCOM03_FELIX_DEPENDENCIES = linux sensor-phy
MCOM03_FELIX_SUBDIR = DDKSource

MCOM03_FELIX_INSTALL_LOCAL = $(@D)/install
MCOM03_FELIX_INSTALL_BIN = $(TARGET_DIR)/usr/bin
MCOM03_FELIX_INSTALL_MOD =  $(TARGET_DIR)/lib/modules/$(LINUX_VERSION_PROBED)
MCOM03_FELIX_INSTALL_CONFIG = $(TARGET_DIR)/usr/share/isp/data

# 1 => enable driver debug functions
MCOM03_FELIX_CI_DEBUG_FUNCTIONS=1
# 0 => internal data generator; 1 => external data generator
MCOM03_FELIX_CI_EXT_DATA_GENERATOR=0

MCOM03_FELIX_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
MCOM03_FELIX_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=$(MCOM03_FELIX_INSTALL_LOCAL)

MCOM03_FELIX_CONF_OPTS += -DLINUX_KERNEL_ARCH="ARCH=$(KERNEL_ARCH)"
MCOM03_FELIX_CONF_OPTS += -DLINUX_KERNEL_CROSS_COMPILE="CROSS_COMPILE=$(TARGET_CROSS)"
MCOM03_FELIX_CONF_OPTS += -DLINUX_KERNEL_BUILD_DIR=$(LINUX_DIR)

MCOM03_FELIX_CONF_OPTS += -DBUILD_SCB_DRIVER=OFF
MCOM03_FELIX_CONF_OPTS += -DBUILD_UNIT_TESTS=OFF
MCOM03_FELIX_CONF_OPTS += -DCI_ALLOC=PAGEALLOC
MCOM03_FELIX_CONF_OPTS += -DCI_BUILD_KERNEL_MODULE=ON
MCOM03_FELIX_CONF_OPTS += -DCI_DEBUG_FUNCTIONS=$(MCOM03_FELIX_CI_DEBUG_FUNCTIONS)
MCOM03_FELIX_CONF_OPTS += -DCI_DEVICE=DEVICE_TREE
MCOM03_FELIX_CONF_OPTS += -DCI_EXT_DATA_GENERATOR=$(MCOM03_FELIX_CI_EXT_DATA_GENERATOR)
MCOM03_FELIX_CONF_OPTS += -DFELIX_PDP=OFF
MCOM03_FELIX_CONF_OPTS += -DSENSORAPI_EUROPA=1
MCOM03_FELIX_CONF_OPTS += -DIMG_SCB_POLLING_MODE=1
MCOM03_FELIX_CONF_OPTS += -DBUILDS_TEST_APPS=1

ifeq ($(BR2_PACKAGE_MCOM03_DMABUF_EXPORTER),y)
MCOM03_FELIX_CONF_OPTS += -DUSE_DMABUF_EXPORTER=1
MCOM03_FELIX_DEPENDENCIES += mcom03-dmabuf-exporter
else
MCOM03_FELIX_CONF_OPTS += -DUSE_DMABUF_EXPORTER=0
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_SENSOR_PARAXDMA_LINUX),y)
MCOM03_FELIX_CONF_OPTS += -DSENSOR_PARAXDMA_LINUX=1
define MCOM03_FELIX_SENSOR_PARAXDMA_CONFIG_INSTALL
	mkdir -p $(MCOM03_FELIX_INSTALL_CONFIG)/paraxdma
	$(INSTALL) -D -m 0644 $(@D)/haps-tests/setup-args-para*.txt $(MCOM03_FELIX_INSTALL_CONFIG)/paraxdma
endef
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_ISPC_TEST),y)
define MCOM03_FELIX_ISPC_TEST_INSTALL
	$(INSTALL) -D -m 0755 $(MCOM03_FELIX_INSTALL_LOCAL)/ISPC/ISPC_test $(MCOM03_FELIX_INSTALL_BIN)/ISPC_test
endef
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_ISPC_LOOP),y)
MCOM03_FELIX_CONF_OPTS += -DCI_PDP_DMABUF=1
MCOM03_FELIX_DEPENDENCIES += libdrm
define MCOM03_FELIX_ISPC_LOOP_INSTALL
	$(INSTALL) -D -m 0755 $(MCOM03_FELIX_INSTALL_LOCAL)/ISPC/ISPC_loop $(MCOM03_FELIX_INSTALL_BIN)/ISPC_loop
endef
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_DRIVER_TEST),y)
define MCOM03_FELIX_DRIVER_TEST_INSTALL
	$(INSTALL) -D -m 0755 $(MCOM03_FELIX_INSTALL_LOCAL)/CI/driver_test $(MCOM03_FELIX_INSTALL_BIN)/driver_test
endef
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_SENSOR_TEST),y)
define MCOM03_FELIX_SENSOR_TEST_INSTALL
	$(INSTALL) -D -m 0755 $(MCOM03_FELIX_INSTALL_LOCAL)/bin/sensor_test $(MCOM03_FELIX_INSTALL_BIN)/sensor_test
endef
endif
ifeq ($(BR2_PACKAGE_MCOM03_FELIX_I2C_TEST),y)
define MCOM03_FELIX_I2C_TEST_INSTALL
	$(INSTALL) -D -m 0755 $(MCOM03_FELIX_INSTALL_LOCAL)/bin/i2c-test $(MCOM03_FELIX_INSTALL_BIN)/i2c-test
endef
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_SENSOR_OV2718),y)
MCOM03_FELIX_CONF_OPTS += -DSENSOR_OV2718=1
else
MCOM03_FELIX_CONF_OPTS += -DSENSOR_OV2718=0
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_SENSOR_OV4689),y)
MCOM03_FELIX_CONF_OPTS += -DSENSOR_OV4689=1
else
MCOM03_FELIX_CONF_OPTS += -DSENSOR_OV4689=0
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_SENSOR_OV5647),y)
MCOM03_FELIX_CONF_OPTS += -DSENSOR_OV5647=1
else
MCOM03_FELIX_CONF_OPTS += -DSENSOR_OV5647=0
endif

ifeq ($(BR2_PACKAGE_MCOM03_FELIX_SENSOR_OV10823),y)
MCOM03_FELIX_CONF_OPTS += -DSENSOR_OV10823=1
else
MCOM03_FELIX_CONF_OPTS += -DSENSOR_OV10823=0
endif

define MCOM03_FELIX_SENSORCFG_INSTALL
	if [ -d $(MCOM03_FELIX_INSTALL_LOCAL)/sensorcfg ]; then \
		set -e; \
		mkdir -p $(TARGET_DIR)/etc/felix; \
		cp -rf $(MCOM03_FELIX_INSTALL_LOCAL)/sensorcfg/* $(TARGET_DIR)/etc/felix; \
	fi
endef

define MCOM03_FELIX_INSTALL_TARGET_CMDS
	make -C $(@D)/$(MCOM03_FELIX_SUBDIR) install
	$(INSTALL) -D -m 0644 $(MCOM03_FELIX_INSTALL_LOCAL)/km/Felix.ko $(MCOM03_FELIX_INSTALL_MOD)/extra/Felix.ko
	depmod -b $(TARGET_DIR) $(LINUX_VERSION_PROBED)
	$(MCOM03_FELIX_SENSOR_PARAXDMA_CONFIG_INSTALL)
	$(MCOM03_FELIX_ISPC_TEST_INSTALL)
	$(MCOM03_FELIX_ISPC_LOOP_INSTALL)
	$(MCOM03_FELIX_DRIVER_TEST_INSTALL)
	$(MCOM03_FELIX_SENSOR_TEST_INSTALL)
	$(MCOM03_FELIX_I2C_TEST_INSTALL)
	$(MCOM03_FELIX_SENSORCFG_INSTALL)
endef

$(eval $(cmake-package))
